import turtle

t = turtle.Turtle()
s = turtle.Screen()
s.bgcolor("#303030")
t.speed(15)

def draw_rectangle(width, height, color ):
    turtle.color(color)
    turtle.begin_fill()
    for _ in range(2):
        turtle.forward(width)
        turtle.right(90)
        turtle.forward(height)
        turtle.right(90)
    turtle.end_fill()

if __name__ == '__name__':
    turtle.speed('show')

turtle.penup()
turtle.goto(-250, 150)
turtle.pendown()
draw_rectangle(500, 90, '#000000')
turtle.penup()
turtle.goto(-250, 60)
turtle.pendown()
draw_rectangle(500, 90, '#ffffff')
turtle.penup()
turtle.goto(-250, -30)
turtle.pendown()
draw_rectangle(500, 90, '#138808')
turtle.penup()
turtle.goto(-250, -150)
turtle.pendown()
turtle.color('#ff0000')
turtle.penup()
turtle.goto(-250, 150)
turtle.pendown()
turtle.begin_fill()
turtle.right(30)
turtle.forward(270)
turtle.right(120)
turtle.forward(270)
turtle.right(120)
turtle.forward(270)
turtle.end_fill()
turtle.hideturtle()
turtle.done()
